import json
import pytest
from unittest.mock import patch, MagicMock
from subprocess import CalledProcessError
from chegi.env_manager import EnvManager


@pytest.fixture
def dummy_json_data():
    return {
        "name": "Python",
        "levels": {"1": ["pip"]},
        "tools": {
            "pip": {"check_cmd": "pip --version"}
        }
    }


@patch("chegi.env_manager.pkg_resources.files")
def test_load_environments_success(mock_files, dummy_json_data):
    """Tests successful loading of JSON environment files."""
    mock_file = MagicMock()
    mock_file.is_file.return_value = True
    mock_file.name = "python.json"
    mock_file.read_text.return_value = json.dumps(dummy_json_data)
    
    mock_dir = MagicMock()
    mock_dir.iterdir.return_value = [mock_file]
    mock_files.return_value = mock_dir

    manager = EnvManager()

    assert "python" in manager.db
    assert manager.db["python"]["name"] == "Python"


@patch("chegi.env_manager.pkg_resources.files")
def test_load_environments_exception(mock_files):
    """Tests that exceptions during loading are silently handled."""
    mock_files.side_effect = Exception("Simulated error")
    
    manager = EnvManager()
    
    assert manager.db == {}


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_language(mock_load, dummy_json_data):
    """Tests retrieving a specific language by name."""
    manager = EnvManager()
    manager.db = {"python": dummy_json_data}
    
    assert manager.get_language("Python") == dummy_json_data
    assert manager.get_language("PYTHON") == dummy_json_data
    assert manager.get_language("ruby") is None


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_tool(mock_load, dummy_json_data):
    """Tests searching for a tool across all environments."""
    manager = EnvManager()
    manager.db = {"python": dummy_json_data}
    
    assert manager.get_tool("pip") == {"check_cmd": "pip --version"}
    assert manager.get_tool("PIP") == {"check_cmd": "pip --version"}
    assert manager.get_tool("gem") is None


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_available_envs(mock_load):
    """Tests retrieving the list of available environment names."""
    manager = EnvManager()
    manager.db = {"python": {}, "ruby": {}, "node": {}}
    
    envs = manager.get_available_envs()
    
    assert sorted(envs) == ["node", "python", "ruby"]


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_env(mock_load, dummy_json_data):
    """Tests that get_env alias correctly calls get_language."""
    manager = EnvManager()
    manager.db = {"python": dummy_json_data}
    
    assert manager.get_env("python") == dummy_json_data
    assert manager.get_env("unknown") is None


# ==========================================
# Gitignore Functionality Tests
# ==========================================

@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_envs_with_gitignore(mock_load):
    """Tests retrieving environments that have a gitignore template."""
    manager = EnvManager()
    manager.db = {
        "python": {"gitignore": ["*.pyc"]},
        "ruby": {},  # No gitignore key
        "node": {"gitignore": ["node_modules/"]}
    }
    
    envs = manager.get_envs_with_gitignore()
    assert sorted(envs) == ["node", "python"]


@patch("chegi.env_manager.EnvManager.load_environments")
@patch("chegi.env_manager.Path.exists")
def test_has_existing_gitignore(mock_exists, mock_load):
    """Tests checking for existing .gitignore files."""
    manager = EnvManager()
    
    # File exists
    mock_exists.return_value = True
    assert manager.has_existing_gitignore("/fake/dir") is True
    
    # File does not exist
    mock_exists.return_value = False
    assert manager.has_existing_gitignore("/fake/dir") is False


@patch("chegi.env_manager.EnvManager.load_environments")
def test_generate_gitignore_empty_list(mock_load):
    """Tests that generating a gitignore with an empty list raises ValueError."""
    manager = EnvManager()
    with pytest.raises(ValueError, match="No environments provided"):
        manager.generate_gitignore([])


@patch("chegi.env_manager.EnvManager.load_environments")
@patch("chegi.env_manager.Path.write_text")
def test_generate_gitignore_success(mock_write_text, mock_load):
    """Tests combining, deduplicating, and writing gitignore templates."""
    manager = EnvManager()
    
    # Mocking get_env to return specific data for this test
    def mock_get_env(name):
        data = {
            "python": {"gitignore": ["*.pyc", ".env"]}, # .env also in global template
            "node": {"gitignore": ["node_modules/"]}
        }
        return data.get(name)
        
    manager.get_env = MagicMock(side_effect=mock_get_env)
    
    manager.generate_gitignore(["python", "node"], "/fake/dir")
    
    written_content = mock_write_text.call_args[0][0]
    
    assert "# .gitignore generated by Chegi for: Python, Node" in written_content
    assert "*.pyc" in written_content
    assert "node_modules/" in written_content
    assert ".DS_Store" in written_content # Check for global template inclusion
    
    # Check for deduplication of rules (e.g., .env)
    assert written_content.count("\n.env\n") <= 1


@patch("chegi.env_manager.EnvManager.load_environments")
@patch("chegi.env_manager.subprocess.run")
def test_is_git_repo(mock_run, mock_load):
    """Tests checking if a directory is a git repository."""
    manager = EnvManager()
    
    # Is a git repo
    mock_run.return_value = MagicMock()
    mock_run.side_effect = None # Clear previous side effects
    assert manager.is_git_repo("/fake/repo") is True
    
    # Not a git repo (command fails)
    mock_run.side_effect = CalledProcessError(128, "git")
    assert manager.is_git_repo("/fake/not_repo") is False
    
    # Git is not installed
    mock_run.side_effect = FileNotFoundError()
    assert manager.is_git_repo("/fake/no_git") is False


@patch("chegi.env_manager.EnvManager.load_environments")
@patch("chegi.env_manager.subprocess.run")
def test_commit_gitignore(mock_run, mock_load):
    """Tests executing git add and commit commands."""
    manager = EnvManager()
    
    commit_msg = manager.commit_gitignore("/fake/repo")
    
    assert commit_msg == "chore(gitignore): auto add .gitignore via cheGi 🐆"
    assert mock_run.call_count == 2
    
    # Check first call: git add
    args_add, _ = mock_run.call_args_list[0]
    assert args_add[0] == ["git", "add", ".gitignore"]
    
    # Check second call: git commit
    args_commit, _ = mock_run.call_args_list[1]
    assert args_commit[0] == ["git", "commit", ".gitignore", "-m", commit_msg]


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_required_package_managers_success(mock_load):
    """Tests extracting a unique set of required package managers from multiple environments."""
    manager = EnvManager()
    manager.db = {
        "python": {"tools": {"pip": {}, "poetry": {}}},
        "node": {"tools": {"npm": {}, "yarn": {}}}
    }
    
    pms = manager.get_required_package_managers(["python", "node"])
    
    assert isinstance(pms, set)
    assert pms == {"pip", "poetry", "npm", "yarn"}


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_required_package_managers_edge_cases(mock_load):
    """Tests package manager extraction with empty lists, invalid envs, or missing tools."""
    manager = EnvManager()
    manager.db = {
        "ruby": {"name": "Ruby"} 
    }
    
    assert manager.get_required_package_managers([]) == set()
    assert manager.get_required_package_managers(["unknown_env"]) == set()
    assert manager.get_required_package_managers(["ruby"]) == set()


@patch("chegi.env_manager.EnvManager.load_environments")
def test_get_required_package_managers_duplicates(mock_load):
    """Tests that duplicate tools across requested environments are returned as a unique set."""
    manager = EnvManager()
    manager.db = {
        "env1": {"tools": {"shared_tool": {}, "tool_a": {}}},
        "env2": {"tools": {"shared_tool": {}, "tool_b": {}}}
    }
    
    pms = manager.get_required_package_managers(["env1", "env2", "env1"])
    
    assert pms == {"shared_tool", "tool_a", "tool_b"}
